delete from t_role where id not in ('01', '02');
delete from t_user where id not in ('01');
delete from t_role_authority where roleid not in ('01', '02');
delete from t_user_role where userid not in ('01');
delete from tbl_customer where id not like '2018091014%';
delete from tbl_supplier where id not like '2018091014%';
delete from tbl_material_category where id not in ('01', '02', '03', '0301', '0302', '0303', '0304', '0305', '0306', '0307', '0399', '99');
delete from tbl_material where modifydate > str_to_date('2019-02-17', '%Y-%m-%d');
delete from tbl_product where modifydate > str_to_date('2019-02-17', '%Y-%m-%d');
delete from tbl_fin_subject where id not in ('0101', '0102', '0103', '0104', '0105', '0106', '0201', '0202', '0501', '0502', '010201', '1544963566933');

TRUNCATE TABLE tbl_bill_dtl_materialin;
TRUNCATE TABLE tbl_bill_dtl_materialout;
TRUNCATE TABLE tbl_bill_dtl_productin;
TRUNCATE TABLE tbl_bill_dtl_productout;
TRUNCATE TABLE tbl_bill_materialin;
TRUNCATE TABLE tbl_bill_materialout;
TRUNCATE TABLE tbl_bill_productin;
TRUNCATE TABLE tbl_bill_productout;
TRUNCATE TABLE tbl_fin_account;
TRUNCATE TABLE tbl_fin_voucher;
TRUNCATE TABLE tbl_fin_voucher_entry;
TRUNCATE TABLE tbl_material_inventory;
TRUNCATE TABLE tbl_material_inventorydetail;
TRUNCATE TABLE tbl_mtl_inout;
TRUNCATE TABLE tbl_order;
TRUNCATE TABLE tbl_order_appointment;
TRUNCATE TABLE tbl_order_item;
TRUNCATE TABLE tbl_product_inout;
TRUNCATE TABLE tbl_product_inventory;
TRUNCATE TABLE tbl_product_inventorydetail;
TRUNCATE TABLE tbl_tmp_material_inventorydetail;
TRUNCATE TABLE tbl_tmp_product_inventorydetail;